name: Build

on:
  push:
    branches:
      - master

jobs:
  release:
    runs-on: macos-latest

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: install opencv
      run: brew install opencv
      
    - name: build
      run: |
        mkdir release && cd release
        cmake -DCMAKE_BUILD_TYPE=Release ..
        make
